/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Product } from "./Product";
import { ProductCountArgs } from "./ProductCountArgs";
import { ProductFindManyArgs } from "./ProductFindManyArgs";
import { ProductFindUniqueArgs } from "./ProductFindUniqueArgs";
import { CreateProductArgs } from "./CreateProductArgs";
import { UpdateProductArgs } from "./UpdateProductArgs";
import { DeleteProductArgs } from "./DeleteProductArgs";
import { CustomerProductPriceFindManyArgs } from "../../customerProductPrice/base/CustomerProductPriceFindManyArgs";
import { CustomerProductPrice } from "../../customerProductPrice/base/CustomerProductPrice";
import { DemandListItemFindManyArgs } from "../../demandListItem/base/DemandListItemFindManyArgs";
import { DemandListItem } from "../../demandListItem/base/DemandListItem";
import { OrderItemFindManyArgs } from "../../orderItem/base/OrderItemFindManyArgs";
import { OrderItem } from "../../orderItem/base/OrderItem";
import { PurchaseItemFindManyArgs } from "../../purchaseItem/base/PurchaseItemFindManyArgs";
import { PurchaseItem } from "../../purchaseItem/base/PurchaseItem";
import { SupplierProductFindManyArgs } from "../../supplierProduct/base/SupplierProductFindManyArgs";
import { SupplierProduct } from "../../supplierProduct/base/SupplierProduct";
import { TagsOnProductFindManyArgs } from "../../tagsOnProduct/base/TagsOnProductFindManyArgs";
import { TagsOnProduct } from "../../tagsOnProduct/base/TagsOnProduct";
import { Category } from "../../category/base/Category";
import { Company } from "../../company/base/Company";
import { ProductService } from "../product.service";
@graphql.Resolver(() => Product)
export class ProductResolverBase {
  constructor(protected readonly service: ProductService) {}

  async _productsMeta(
    @graphql.Args() args: ProductCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Product])
  async products(
    @graphql.Args() args: ProductFindManyArgs
  ): Promise<Product[]> {
    return this.service.products(args);
  }

  @graphql.Query(() => Product, { nullable: true })
  async product(
    @graphql.Args() args: ProductFindUniqueArgs
  ): Promise<Product | null> {
    const result = await this.service.product(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Product)
  async createProduct(
    @graphql.Args() args: CreateProductArgs
  ): Promise<Product> {
    return await this.service.createProduct({
      ...args,
      data: {
        ...args.data,

        category: {
          connect: args.data.category,
        },

        company: {
          connect: args.data.company,
        },
      },
    });
  }

  @graphql.Mutation(() => Product)
  async updateProduct(
    @graphql.Args() args: UpdateProductArgs
  ): Promise<Product | null> {
    try {
      return await this.service.updateProduct({
        ...args,
        data: {
          ...args.data,

          category: {
            connect: args.data.category,
          },

          company: {
            connect: args.data.company,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Product)
  async deleteProduct(
    @graphql.Args() args: DeleteProductArgs
  ): Promise<Product | null> {
    try {
      return await this.service.deleteProduct(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [CustomerProductPrice], {
    name: "customerPrices",
  })
  async findCustomerPrices(
    @graphql.Parent() parent: Product,
    @graphql.Args() args: CustomerProductPriceFindManyArgs
  ): Promise<CustomerProductPrice[]> {
    const results = await this.service.findCustomerPrices(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [DemandListItem], { name: "demandListItem" })
  async findDemandListItem(
    @graphql.Parent() parent: Product,
    @graphql.Args() args: DemandListItemFindManyArgs
  ): Promise<DemandListItem[]> {
    const results = await this.service.findDemandListItem(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [OrderItem], { name: "orderItems" })
  async findOrderItems(
    @graphql.Parent() parent: Product,
    @graphql.Args() args: OrderItemFindManyArgs
  ): Promise<OrderItem[]> {
    const results = await this.service.findOrderItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [PurchaseItem], { name: "purchaseItem" })
  async findPurchaseItem(
    @graphql.Parent() parent: Product,
    @graphql.Args() args: PurchaseItemFindManyArgs
  ): Promise<PurchaseItem[]> {
    const results = await this.service.findPurchaseItem(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [SupplierProduct], { name: "supplierProducts" })
  async findSupplierProducts(
    @graphql.Parent() parent: Product,
    @graphql.Args() args: SupplierProductFindManyArgs
  ): Promise<SupplierProduct[]> {
    const results = await this.service.findSupplierProducts(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [TagsOnProduct], { name: "tags" })
  async findTags(
    @graphql.Parent() parent: Product,
    @graphql.Args() args: TagsOnProductFindManyArgs
  ): Promise<TagsOnProduct[]> {
    const results = await this.service.findTags(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Category, {
    nullable: true,
    name: "category",
  })
  async getCategory(
    @graphql.Parent() parent: Product
  ): Promise<Category | null> {
    const result = await this.service.getCategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Company, {
    nullable: true,
    name: "company",
  })
  async getCompany(@graphql.Parent() parent: Product): Promise<Company | null> {
    const result = await this.service.getCompany(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
