/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PurchaseService } from "../purchase.service";
import { PurchaseCreateInput } from "./PurchaseCreateInput";
import { Purchase } from "./Purchase";
import { PurchaseFindManyArgs } from "./PurchaseFindManyArgs";
import { PurchaseWhereUniqueInput } from "./PurchaseWhereUniqueInput";
import { PurchaseUpdateInput } from "./PurchaseUpdateInput";
import { PurchaseItemFindManyArgs } from "../../purchaseItem/base/PurchaseItemFindManyArgs";
import { PurchaseItem } from "../../purchaseItem/base/PurchaseItem";
import { PurchaseItemWhereUniqueInput } from "../../purchaseItem/base/PurchaseItemWhereUniqueInput";
import { SupplierPaymentFindManyArgs } from "../../supplierPayment/base/SupplierPaymentFindManyArgs";
import { SupplierPayment } from "../../supplierPayment/base/SupplierPayment";
import { SupplierPaymentWhereUniqueInput } from "../../supplierPayment/base/SupplierPaymentWhereUniqueInput";

export class PurchaseControllerBase {
  constructor(protected readonly service: PurchaseService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Purchase })
  async createPurchase(
    @common.Body() data: PurchaseCreateInput
  ): Promise<Purchase> {
    return await this.service.createPurchase({
      data: {
        ...data,

        demandList: {
          connect: data.demandList,
        },

        supplier: {
          connect: data.supplier,
        },
      },
      select: {
        createdAt: true,

        demandList: {
          select: {
            id: true,
          },
        },

        id: true,
        paidAmount: true,
        purchaseDate: true,
        purchaseNumber: true,

        supplier: {
          select: {
            id: true,
          },
        },

        totalAmount: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Purchase] })
  @ApiNestedQuery(PurchaseFindManyArgs)
  async purchases(@common.Req() request: Request): Promise<Purchase[]> {
    const args = plainToClass(PurchaseFindManyArgs, request.query);
    return this.service.purchases({
      ...args,
      select: {
        createdAt: true,

        demandList: {
          select: {
            id: true,
          },
        },

        id: true,
        paidAmount: true,
        purchaseDate: true,
        purchaseNumber: true,

        supplier: {
          select: {
            id: true,
          },
        },

        totalAmount: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Purchase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async purchase(
    @common.Param() params: PurchaseWhereUniqueInput
  ): Promise<Purchase | null> {
    const result = await this.service.purchase({
      where: params,
      select: {
        createdAt: true,

        demandList: {
          select: {
            id: true,
          },
        },

        id: true,
        paidAmount: true,
        purchaseDate: true,
        purchaseNumber: true,

        supplier: {
          select: {
            id: true,
          },
        },

        totalAmount: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Purchase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePurchase(
    @common.Param() params: PurchaseWhereUniqueInput,
    @common.Body() data: PurchaseUpdateInput
  ): Promise<Purchase | null> {
    try {
      return await this.service.updatePurchase({
        where: params,
        data: {
          ...data,

          demandList: {
            connect: data.demandList,
          },

          supplier: {
            connect: data.supplier,
          },
        },
        select: {
          createdAt: true,

          demandList: {
            select: {
              id: true,
            },
          },

          id: true,
          paidAmount: true,
          purchaseDate: true,
          purchaseNumber: true,

          supplier: {
            select: {
              id: true,
            },
          },

          totalAmount: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Purchase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePurchase(
    @common.Param() params: PurchaseWhereUniqueInput
  ): Promise<Purchase | null> {
    try {
      return await this.service.deletePurchase({
        where: params,
        select: {
          createdAt: true,

          demandList: {
            select: {
              id: true,
            },
          },

          id: true,
          paidAmount: true,
          purchaseDate: true,
          purchaseNumber: true,

          supplier: {
            select: {
              id: true,
            },
          },

          totalAmount: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/items")
  @ApiNestedQuery(PurchaseItemFindManyArgs)
  async findItems(
    @common.Req() request: Request,
    @common.Param() params: PurchaseWhereUniqueInput
  ): Promise<PurchaseItem[]> {
    const query = plainToClass(PurchaseItemFindManyArgs, request.query);
    const results = await this.service.findItems(params.id, {
      ...query,
      select: {
        createdAt: true,

        demandListItem: {
          select: {
            id: true,
          },
        },

        id: true,

        product: {
          select: {
            id: true,
          },
        },

        purchase: {
          select: {
            id: true,
          },
        },

        purchasePrice: true,
        quantity: true,

        supplierProduct: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/items")
  async connectItems(
    @common.Param() params: PurchaseWhereUniqueInput,
    @common.Body() body: PurchaseItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      items: {
        connect: body,
      },
    };
    await this.service.updatePurchase({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/items")
  async updateItems(
    @common.Param() params: PurchaseWhereUniqueInput,
    @common.Body() body: PurchaseItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      items: {
        set: body,
      },
    };
    await this.service.updatePurchase({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/items")
  async disconnectItems(
    @common.Param() params: PurchaseWhereUniqueInput,
    @common.Body() body: PurchaseItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      items: {
        disconnect: body,
      },
    };
    await this.service.updatePurchase({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/payments")
  @ApiNestedQuery(SupplierPaymentFindManyArgs)
  async findPayments(
    @common.Req() request: Request,
    @common.Param() params: PurchaseWhereUniqueInput
  ): Promise<SupplierPayment[]> {
    const query = plainToClass(SupplierPaymentFindManyArgs, request.query);
    const results = await this.service.findPayments(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        notes: true,
        paymentDate: true,
        paymentMethod: true,

        purchase: {
          select: {
            id: true,
          },
        },

        reference: true,

        supplier: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/payments")
  async connectPayments(
    @common.Param() params: PurchaseWhereUniqueInput,
    @common.Body() body: SupplierPaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        connect: body,
      },
    };
    await this.service.updatePurchase({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/payments")
  async updatePayments(
    @common.Param() params: PurchaseWhereUniqueInput,
    @common.Body() body: SupplierPaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        set: body,
      },
    };
    await this.service.updatePurchase({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/payments")
  async disconnectPayments(
    @common.Param() params: PurchaseWhereUniqueInput,
    @common.Body() body: SupplierPaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        disconnect: body,
      },
    };
    await this.service.updatePurchase({
      where: params,
      data,
      select: { id: true },
    });
  }
}
