/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  ValidateNested,
  IsString,
  IsOptional,
  IsNumber,
  Max,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { DemandList } from "../../demandList/base/DemandList";
import { PurchaseItem } from "../../purchaseItem/base/PurchaseItem";
import { SupplierPayment } from "../../supplierPayment/base/SupplierPayment";
import { Supplier } from "../../supplier/base/Supplier";

@ObjectType()
class Purchase {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: () => DemandList,
  })
  @ValidateNested()
  @Type(() => DemandList)
  demandList?: DemandList;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => [PurchaseItem],
  })
  @ValidateNested()
  @Type(() => PurchaseItem)
  @IsOptional()
  items?: Array<PurchaseItem>;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Number)
  paidAmount!: number;

  @ApiProperty({
    required: false,
    type: () => [SupplierPayment],
  })
  @ValidateNested()
  @Type(() => SupplierPayment)
  @IsOptional()
  payments?: Array<SupplierPayment>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  purchaseDate!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  purchaseNumber!: string;

  @ApiProperty({
    required: true,
    type: () => Supplier,
  })
  @ValidateNested()
  @Type(() => Supplier)
  supplier?: Supplier;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Number)
  totalAmount!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Purchase as Purchase };
