/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DemandListWhereUniqueInput } from "../../demandList/base/DemandListWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsNumber,
  Max,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { PurchaseItemUpdateManyWithoutPurchasesInput } from "./PurchaseItemUpdateManyWithoutPurchasesInput";
import { SupplierPaymentUpdateManyWithoutPurchasesInput } from "./SupplierPaymentUpdateManyWithoutPurchasesInput";
import { SupplierWhereUniqueInput } from "../../supplier/base/SupplierWhereUniqueInput";

@InputType()
class PurchaseUpdateInput {
  @ApiProperty({
    required: false,
    type: () => DemandListWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DemandListWhereUniqueInput)
  @IsOptional()
  @Field(() => DemandListWhereUniqueInput, {
    nullable: true,
  })
  demandList?: DemandListWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => PurchaseItemUpdateManyWithoutPurchasesInput,
  })
  @ValidateNested()
  @Type(() => PurchaseItemUpdateManyWithoutPurchasesInput)
  @IsOptional()
  @Field(() => PurchaseItemUpdateManyWithoutPurchasesInput, {
    nullable: true,
  })
  items?: PurchaseItemUpdateManyWithoutPurchasesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  paidAmount?: number;

  @ApiProperty({
    required: false,
    type: () => SupplierPaymentUpdateManyWithoutPurchasesInput,
  })
  @ValidateNested()
  @Type(() => SupplierPaymentUpdateManyWithoutPurchasesInput)
  @IsOptional()
  @Field(() => SupplierPaymentUpdateManyWithoutPurchasesInput, {
    nullable: true,
  })
  payments?: SupplierPaymentUpdateManyWithoutPurchasesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  purchaseNumber?: string;

  @ApiProperty({
    required: false,
    type: () => SupplierWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SupplierWhereUniqueInput)
  @IsOptional()
  @Field(() => SupplierWhereUniqueInput, {
    nullable: true,
  })
  supplier?: SupplierWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  totalAmount?: number;
}

export { PurchaseUpdateInput as PurchaseUpdateInput };
