import { Category } from "../category/Category";
import { Company } from "../company/Company";
import { CustomerProductPrice } from "../customerProductPrice/CustomerProductPrice";
import { DemandListItem } from "../demandListItem/DemandListItem";
import { OrderItem } from "../orderItem/OrderItem";
import { PurchaseItem } from "../purchaseItem/PurchaseItem";
import { SupplierProduct } from "../supplierProduct/SupplierProduct";
import { TagsOnProduct } from "../tagsOnProduct/TagsOnProduct";

export type Product = {
  category?: Category;
  company?: Company;
  createdAt: Date;
  customerPrices?: Array<CustomerProductPrice>;
  demandListItem?: Array<DemandListItem>;
  description: string | null;
  expiryDate: Date | null;
  id: string;
  name: string;
  orderItems?: Array<OrderItem>;
  purchaseItem?: Array<PurchaseItem>;
  purchasePrice: number;
  reorderLevel: number | null;
  retailPrice: number | null;
  sellPrice: number;
  size: string | null;
  sku: string;
  stockQuantity: number;
  supplierProducts?: Array<SupplierProduct>;
  tags?: Array<TagsOnProduct>;
  updatedAt: Date;
  weight: number | null;
  weightUnit?: "G" | "ML" | "KG" | "L" | null;
};
