import { CategoryWhereUniqueInput } from "../category/CategoryWhereUniqueInput";
import { CompanyWhereUniqueInput } from "../company/CompanyWhereUniqueInput";
import { CustomerProductPriceCreateNestedManyWithoutProductsInput } from "./CustomerProductPriceCreateNestedManyWithoutProductsInput";
import { DemandListItemCreateNestedManyWithoutProductsInput } from "./DemandListItemCreateNestedManyWithoutProductsInput";
import { OrderItemCreateNestedManyWithoutProductsInput } from "./OrderItemCreateNestedManyWithoutProductsInput";
import { PurchaseItemCreateNestedManyWithoutProductsInput } from "./PurchaseItemCreateNestedManyWithoutProductsInput";
import { SupplierProductCreateNestedManyWithoutProductsInput } from "./SupplierProductCreateNestedManyWithoutProductsInput";
import { TagsOnProductCreateNestedManyWithoutProductsInput } from "./TagsOnProductCreateNestedManyWithoutProductsInput";

export type ProductCreateInput = {
  category: CategoryWhereUniqueInput;
  company: CompanyWhereUniqueInput;
  customerPrices?: CustomerProductPriceCreateNestedManyWithoutProductsInput;
  demandListItem?: DemandListItemCreateNestedManyWithoutProductsInput;
  description?: string | null;
  expiryDate?: Date | null;
  name: string;
  orderItems?: OrderItemCreateNestedManyWithoutProductsInput;
  purchaseItem?: PurchaseItemCreateNestedManyWithoutProductsInput;
  purchasePrice: number;
  reorderLevel?: number | null;
  retailPrice?: number | null;
  sellPrice: number;
  size?: string | null;
  sku: string;
  stockQuantity: number;
  supplierProducts?: SupplierProductCreateNestedManyWithoutProductsInput;
  tags?: TagsOnProductCreateNestedManyWithoutProductsInput;
  weight?: number | null;
  weightUnit?: "G" | "ML" | "KG" | "L" | null;
};
