/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DemandListItemUpdateManyWithoutOrderItemsInput } from "./DemandListItemUpdateManyWithoutOrderItemsInput";
import {
  ValidateNested,
  IsOptional,
  IsInt,
  Max,
  IsNumber,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
import { EnumOrderItemStatus } from "./EnumOrderItemStatus";

@InputType()
class OrderItemUpdateInput {
  @ApiProperty({
    required: false,
    type: () => DemandListItemUpdateManyWithoutOrderItemsInput,
  })
  @ValidateNested()
  @Type(() => DemandListItemUpdateManyWithoutOrderItemsInput)
  @IsOptional()
  @Field(() => DemandListItemUpdateManyWithoutOrderItemsInput, {
    nullable: true,
  })
  demandListItems?: DemandListItemUpdateManyWithoutOrderItemsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  fulfilledQuantity?: number;

  @ApiProperty({
    required: false,
    type: () => OrderWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OrderWhereUniqueInput)
  @IsOptional()
  @Field(() => OrderWhereUniqueInput, {
    nullable: true,
  })
  order?: OrderWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ProductWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @IsOptional()
  @Field(() => ProductWhereUniqueInput, {
    nullable: true,
  })
  product?: ProductWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  quantity?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  sellPrice?: number;

  @ApiProperty({
    required: false,
    enum: EnumOrderItemStatus,
  })
  @IsEnum(EnumOrderItemStatus)
  @IsOptional()
  @Field(() => EnumOrderItemStatus, {
    nullable: true,
  })
  status?: "PENDING" | "PARTIAL" | "COMPLETE" | "CANCELLED";
}

export { OrderItemUpdateInput as OrderItemUpdateInput };
