/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsNumber,
  Max,
  IsDate,
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  ValidateNested,
} from "class-validator";

import { Type } from "class-transformer";
import { EnumSupplierPaymentPaymentMethod } from "./EnumSupplierPaymentPaymentMethod";
import { Purchase } from "../../purchase/base/Purchase";
import { Supplier } from "../../supplier/base/Supplier";

@ObjectType()
class SupplierPayment {
  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Number)
  amount!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  notes!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  paymentDate!: Date;

  @ApiProperty({
    required: true,
    enum: EnumSupplierPaymentPaymentMethod,
  })
  @IsEnum(EnumSupplierPaymentPaymentMethod)
  @Field(() => EnumSupplierPaymentPaymentMethod, {
    nullable: true,
  })
  paymentMethod?: "CASH" | "BANK_TRANSFER" | "CHECK" | "CREDIT" | "OTHER";

  @ApiProperty({
    required: false,
    type: () => Purchase,
  })
  @ValidateNested()
  @Type(() => Purchase)
  @IsOptional()
  purchase?: Purchase | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reference!: string | null;

  @ApiProperty({
    required: true,
    type: () => Supplier,
  })
  @ValidateNested()
  @Type(() => Supplier)
  supplier?: Supplier;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { SupplierPayment as SupplierPayment };
