/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsNumber,
  Max,
} from "class-validator";
import { DemandListUpdateManyWithoutSuppliersInput } from "./DemandListUpdateManyWithoutSuppliersInput";
import { Type } from "class-transformer";
import { SupplierPaymentUpdateManyWithoutSuppliersInput } from "./SupplierPaymentUpdateManyWithoutSuppliersInput";
import { PurchaseUpdateManyWithoutSuppliersInput } from "./PurchaseUpdateManyWithoutSuppliersInput";
import { SupplierProductUpdateManyWithoutSuppliersInput } from "./SupplierProductUpdateManyWithoutSuppliersInput";

@InputType()
class SupplierUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactPerson?: string;

  @ApiProperty({
    required: false,
    type: () => DemandListUpdateManyWithoutSuppliersInput,
  })
  @ValidateNested()
  @Type(() => DemandListUpdateManyWithoutSuppliersInput)
  @IsOptional()
  @Field(() => DemandListUpdateManyWithoutSuppliersInput, {
    nullable: true,
  })
  demandLists?: DemandListUpdateManyWithoutSuppliersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => SupplierPaymentUpdateManyWithoutSuppliersInput,
  })
  @ValidateNested()
  @Type(() => SupplierPaymentUpdateManyWithoutSuppliersInput)
  @IsOptional()
  @Field(() => SupplierPaymentUpdateManyWithoutSuppliersInput, {
    nullable: true,
  })
  payments?: SupplierPaymentUpdateManyWithoutSuppliersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string;

  @ApiProperty({
    required: false,
    type: () => PurchaseUpdateManyWithoutSuppliersInput,
  })
  @ValidateNested()
  @Type(() => PurchaseUpdateManyWithoutSuppliersInput)
  @IsOptional()
  @Field(() => PurchaseUpdateManyWithoutSuppliersInput, {
    nullable: true,
  })
  purchases?: PurchaseUpdateManyWithoutSuppliersInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  reliabilityScore?: number | null;

  @ApiProperty({
    required: false,
    type: () => SupplierProductUpdateManyWithoutSuppliersInput,
  })
  @ValidateNested()
  @Type(() => SupplierProductUpdateManyWithoutSuppliersInput)
  @IsOptional()
  @Field(() => SupplierProductUpdateManyWithoutSuppliersInput, {
    nullable: true,
  })
  supplierProducts?: SupplierProductUpdateManyWithoutSuppliersInput;
}

export { SupplierUpdateInput as SupplierUpdateInput };
