/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { DemandListWhereUniqueInput } from "../../demandList/base/DemandListWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { OrderItemWhereUniqueInput } from "../../orderItem/base/OrderItemWhereUniqueInput";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
import { PurchaseItemWhereUniqueInput } from "../../purchaseItem/base/PurchaseItemWhereUniqueInput";
import { IntFilter } from "../../util/IntFilter";
import { EnumDemandListItemStatus } from "./EnumDemandListItemStatus";

@InputType()
class DemandListItemWhereInput {
  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  confirmedQuantity?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => DemandListWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DemandListWhereUniqueInput)
  @IsOptional()
  @Field(() => DemandListWhereUniqueInput, {
    nullable: true,
  })
  demandList?: DemandListWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => OrderItemWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OrderItemWhereUniqueInput)
  @IsOptional()
  @Field(() => OrderItemWhereUniqueInput, {
    nullable: true,
  })
  orderItem?: OrderItemWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ProductWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @IsOptional()
  @Field(() => ProductWhereUniqueInput, {
    nullable: true,
  })
  product?: ProductWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => PurchaseItemWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PurchaseItemWhereUniqueInput)
  @IsOptional()
  @Field(() => PurchaseItemWhereUniqueInput, {
    nullable: true,
  })
  purchaseItem?: PurchaseItemWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  requestedQuantity?: IntFilter;

  @ApiProperty({
    required: false,
    enum: EnumDemandListItemStatus,
  })
  @IsEnum(EnumDemandListItemStatus)
  @IsOptional()
  @Field(() => EnumDemandListItemStatus, {
    nullable: true,
  })
  status?:
    | "PENDING"
    | "CONFIRMED"
    | "UNAVAILABLE"
    | "TRANSFERRED"
    | "PURCHASED"
    | "CANCELLED";

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeFilter;
}

export { DemandListItemWhereInput as DemandListItemWhereInput };
